// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvailableSlots = `-- name: GetAvailableSlots :many
WITH slots AS (
    -- Las columnas start_time/end_time no tienen timezone: representan hora local
    -- del consultorio (America/Bogota), no UTC. Sin el AT TIME ZONE explícito, Postgres
    -- las interpretaría como UTC al convertirlas a timestamptz (bug detectado en pruebas).
    SELECT (generate_series(
        ($2::date + a.start_time) AT TIME ZONE 'America/Bogota',
        (($2::date + a.end_time) AT TIME ZONE 'America/Bogota') - (dp.default_slot_minutes || ' minutes')::interval,
        (dp.default_slot_minutes || ' minutes')::interval
    ))::timestamptz AS slot_start
    FROM availability a
    JOIN doctor_profiles dp ON dp.id = a.doctor_id
    WHERE a.doctor_id = $1
      AND a.day_of_week = EXTRACT(DOW FROM $2::date)
)
SELECT s.slot_start
FROM slots s
WHERE NOT EXISTS (
    SELECT 1 FROM appointments ap
    WHERE ap.doctor_id = $1
      AND ap.slot_start = s.slot_start
      AND ap.status IN ('pending', 'confirmed')
)
ORDER BY s.slot_start
`

type GetAvailableSlotsParams struct {
	DoctorID   pgtype.UUID `json:"doctor_id"`
	TargetDate pgtype.Date `json:"target_date"`
}

func (q *Queries) GetAvailableSlots(ctx context.Context, arg GetAvailableSlotsParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, getAvailableSlots, arg.DoctorID, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var slot_start pgtype.Timestamptz
		if err := rows.Scan(&slot_start); err != nil {
			return nil, err
		}
		items = append(items, slot_start)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
