// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAppointment = `-- name: CancelAppointment :one
UPDATE appointments
SET status = 'cancelled'
WHERE id = $1 AND status IN ('pending', 'confirmed')
RETURNING id, patient_id, doctor_id, slot_start, slot_end, status, created_at
`

func (q *Queries) CancelAppointment(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, cancelAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.SlotStart,
		&i.SlotEnd,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (patient_id, doctor_id, slot_start, slot_end, status)
VALUES ($1, $2, $3, $4, 'pending')
ON CONFLICT (doctor_id, slot_start) WHERE status IN ('pending', 'confirmed')
DO NOTHING
RETURNING id, patient_id, doctor_id, slot_start, slot_end, status, created_at
`

type CreateAppointmentParams struct {
	PatientID pgtype.UUID        `json:"patient_id"`
	DoctorID  pgtype.UUID        `json:"doctor_id"`
	SlotStart pgtype.Timestamptz `json:"slot_start"`
	SlotEnd   pgtype.Timestamptz `json:"slot_end"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.PatientID,
		arg.DoctorID,
		arg.SlotStart,
		arg.SlotEnd,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.SlotStart,
		&i.SlotEnd,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, patient_id, doctor_id, slot_start, slot_end, status, created_at FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.SlotStart,
		&i.SlotEnd,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAppointmentForReminder = `-- name: GetAppointmentForReminder :one
SELECT ap.id, ap.slot_start, ap.status,
       u.email AS patient_email, u.full_name AS patient_name,
       du.full_name AS doctor_name
FROM appointments ap
JOIN users u ON u.id = ap.patient_id
JOIN doctor_profiles dp ON dp.id = ap.doctor_id
JOIN users du ON du.id = dp.user_id
WHERE ap.id = $1
`

type GetAppointmentForReminderRow struct {
	ID           pgtype.UUID        `json:"id"`
	SlotStart    pgtype.Timestamptz `json:"slot_start"`
	Status       AppointmentStatus  `json:"status"`
	PatientEmail string             `json:"patient_email"`
	PatientName  string             `json:"patient_name"`
	DoctorName   string             `json:"doctor_name"`
}

func (q *Queries) GetAppointmentForReminder(ctx context.Context, id pgtype.UUID) (GetAppointmentForReminderRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentForReminder, id)
	var i GetAppointmentForReminderRow
	err := row.Scan(
		&i.ID,
		&i.SlotStart,
		&i.Status,
		&i.PatientEmail,
		&i.PatientName,
		&i.DoctorName,
	)
	return i, err
}

const getAvailableSlots = `-- name: GetAvailableSlots :many
WITH slots AS (
    -- Las columnas start_time/end_time no tienen timezone: representan hora local
    -- del consultorio (America/Bogota), no UTC. Sin el AT TIME ZONE explícito, Postgres
    -- las interpretaría como UTC al convertirlas a timestamptz (bug detectado en pruebas).
    SELECT (generate_series(
        ($2::date + a.start_time) AT TIME ZONE 'America/Bogota',
        (($2::date + a.end_time) AT TIME ZONE 'America/Bogota') - (dp.default_slot_minutes || ' minutes')::interval,
        (dp.default_slot_minutes || ' minutes')::interval
    ))::timestamptz AS slot_start
    FROM availability a
    JOIN doctor_profiles dp ON dp.id = a.doctor_id
    WHERE a.doctor_id = $1
      AND a.day_of_week = EXTRACT(DOW FROM $2::date)
)
SELECT s.slot_start
FROM slots s
WHERE NOT EXISTS (
    SELECT 1 FROM appointments ap
    WHERE ap.doctor_id = $1
      AND ap.slot_start = s.slot_start
      AND ap.status IN ('pending', 'confirmed')
)
ORDER BY s.slot_start
`

type GetAvailableSlotsParams struct {
	DoctorID   pgtype.UUID `json:"doctor_id"`
	TargetDate pgtype.Date `json:"target_date"`
}

func (q *Queries) GetAvailableSlots(ctx context.Context, arg GetAvailableSlotsParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, getAvailableSlots, arg.DoctorID, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var slot_start pgtype.Timestamptz
		if err := rows.Scan(&slot_start); err != nil {
			return nil, err
		}
		items = append(items, slot_start)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseExpiredPendingAppointments = `-- name: ReleaseExpiredPendingAppointments :many
UPDATE appointments
SET status = 'cancelled'
WHERE status = 'pending'
  AND created_at < now() - ($1::int * interval '1 minute')
RETURNING id, doctor_id, slot_start
`

type ReleaseExpiredPendingAppointmentsRow struct {
	ID        pgtype.UUID        `json:"id"`
	DoctorID  pgtype.UUID        `json:"doctor_id"`
	SlotStart pgtype.Timestamptz `json:"slot_start"`
}

func (q *Queries) ReleaseExpiredPendingAppointments(ctx context.Context, holdMinutes int32) ([]ReleaseExpiredPendingAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, releaseExpiredPendingAppointments, holdMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseExpiredPendingAppointmentsRow
	for rows.Next() {
		var i ReleaseExpiredPendingAppointmentsRow
		if err := rows.Scan(&i.ID, &i.DoctorID, &i.SlotStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
