// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctor_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDoctorProfile = `-- name: CreateDoctorProfile :one
INSERT INTO doctor_profiles (user_id, specialty)
VALUES ($1, $2)
RETURNING id, user_id, specialty, default_slot_minutes, created_at
`

type CreateDoctorProfileParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Specialty string      `json:"specialty"`
}

func (q *Queries) CreateDoctorProfile(ctx context.Context, arg CreateDoctorProfileParams) (DoctorProfile, error) {
	row := q.db.QueryRow(ctx, createDoctorProfile, arg.UserID, arg.Specialty)
	var i DoctorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialty,
		&i.DefaultSlotMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const getDoctorProfileByUserID = `-- name: GetDoctorProfileByUserID :one
SELECT id, user_id, specialty, default_slot_minutes, created_at FROM doctor_profiles
WHERE user_id = $1
`

func (q *Queries) GetDoctorProfileByUserID(ctx context.Context, userID pgtype.UUID) (DoctorProfile, error) {
	row := q.db.QueryRow(ctx, getDoctorProfileByUserID, userID)
	var i DoctorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialty,
		&i.DefaultSlotMinutes,
		&i.CreatedAt,
	)
	return i, err
}
