// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctor_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDoctorProfile = `-- name: CreateDoctorProfile :one
INSERT INTO doctor_profiles (user_id)
VALUES ($1)
RETURNING id, user_id, default_slot_minutes, created_at
`

func (q *Queries) CreateDoctorProfile(ctx context.Context, userID pgtype.UUID) (DoctorProfile, error) {
	row := q.db.QueryRow(ctx, createDoctorProfile, userID)
	var i DoctorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefaultSlotMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const getDoctorProfileByUserID = `-- name: GetDoctorProfileByUserID :one
SELECT id, user_id, default_slot_minutes, created_at FROM doctor_profiles
WHERE user_id = $1
`

func (q *Queries) GetDoctorProfileByUserID(ctx context.Context, userID pgtype.UUID) (DoctorProfile, error) {
	row := q.db.QueryRow(ctx, getDoctorProfileByUserID, userID)
	var i DoctorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefaultSlotMinutes,
		&i.CreatedAt,
	)
	return i, err
}
