// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddDoctorSpecialty(ctx context.Context, arg AddDoctorSpecialtyParams) error
	CancelAppointment(ctx context.Context, id pgtype.UUID) (Appointment, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (Availability, error)
	CreateDoctorProfile(ctx context.Context, userID pgtype.UUID) (DoctorProfile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAppointmentByID(ctx context.Context, id pgtype.UUID) (Appointment, error)
	GetAvailableSlots(ctx context.Context, arg GetAvailableSlotsParams) ([]pgtype.Timestamptz, error)
	GetDoctorProfileByUserID(ctx context.Context, userID pgtype.UUID) (DoctorProfile, error)
	GetDoctorSpecialties(ctx context.Context, doctorID pgtype.UUID) ([]Specialty, error)
	GetOrCreateSpecialty(ctx context.Context, name string) (Specialty, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
