// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: specialties.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDoctorSpecialty = `-- name: AddDoctorSpecialty :exec
INSERT INTO doctor_specialties (doctor_id, specialty_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddDoctorSpecialtyParams struct {
	DoctorID    pgtype.UUID `json:"doctor_id"`
	SpecialtyID pgtype.UUID `json:"specialty_id"`
}

func (q *Queries) AddDoctorSpecialty(ctx context.Context, arg AddDoctorSpecialtyParams) error {
	_, err := q.db.Exec(ctx, addDoctorSpecialty, arg.DoctorID, arg.SpecialtyID)
	return err
}

const getDoctorSpecialties = `-- name: GetDoctorSpecialties :many
SELECT s.id, s.name FROM specialties s
JOIN doctor_specialties ds ON ds.specialty_id = s.id
WHERE ds.doctor_id = $1
`

func (q *Queries) GetDoctorSpecialties(ctx context.Context, doctorID pgtype.UUID) ([]Specialty, error) {
	rows, err := q.db.Query(ctx, getDoctorSpecialties, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialty
	for rows.Next() {
		var i Specialty
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateSpecialty = `-- name: GetOrCreateSpecialty :one
INSERT INTO specialties (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) GetOrCreateSpecialty(ctx context.Context, name string) (Specialty, error) {
	row := q.db.QueryRow(ctx, getOrCreateSpecialty, name)
	var i Specialty
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
